In [ ]:
import numpy as np

#Numpy

Linear algebra library for Python; runs c program using python; makes it very fast.

#Numpy Arrays
Vectors - 1D; Matrices - 2D;

pydata.org

In [ ]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)  #python list to numpy array

array([1, 2, 3])

In [ ]:
mymatrix=[[1,2,3],[4,5,6],[7,8,9]]
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(mymatrix)  #python complex list to numpy array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(np.array(mymatrix))

numpy.ndarray

#Built in methods

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [ ]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.zeros(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((10,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0,5)  #returns evenly spaced numbers between range

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [ ]:
np.linspace(0,5,4) # 4 values evenly spaced between 0 to 5

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(5) #generates 2d array with 1 filled in diagonal and rest with 0s

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2)  # 1D array #rand - random values generated will have uniform disctribution

array([0.89998362, 0.16177366])

In [ ]:
np.random.rand(3,2) #2D array

array([[0.69161825, 0.30004154],
       [0.58127002, 0.59101998],
       [0.83947366, 0.4993303 ]])

In [ ]:
np.random.rand(2,4,3)  #3D array

array([[[0.83708654, 0.99114066, 0.73393905],
        [0.52636397, 0.51782032, 0.43865088],
        [0.78285433, 0.66334224, 0.34043531],
        [0.21272156, 0.73107254, 0.33245169]],

       [[0.04510748, 0.76403112, 0.2359573 ],
        [0.2884821 , 0.78609314, 0.60462352],
        [0.97743269, 0.71212675, 0.86148309],
        [0.07676991, 0.5393179 , 0.81785377]]])

In [ ]:
np.random.randn(2)  #randn creates normal distribution

array([-1.72392115,  0.42531714])

In [ ]:
np.random.randn(3,2,1)

array([[[ 1.4828227 ],
        [-0.48371719]],

       [[-0.49071795],
        [ 0.34059163]],

       [[ 0.14083448],
        [ 0.16689763]]])

In [ ]:
np.random.randint(3,10)  #generates a random value between 3 and 10 ; 10 will not be included.

4

In [ ]:
np.random.randint(1,100,4) #4 random numbers between 1 and 100 in the form of array

array([68, 67, 94, 19])

#Array Attributes and Methods

In [ ]:
arr=np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
ranArr=np.random.randint(0,50,10)
ranArr

array([18, 25, 43, 32, 30, 49,  9,  5, 26, 25])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
ranArr

array([18, 25, 43, 32, 30, 49,  9,  5, 26, 25])

In [ ]:
ranArr.max()

49

In [ ]:
ranArr.min()

5

In [ ]:
ranArr.argmax()  #returns index of the max value.  #if theren are more than one 5s in the array, then it will return the index of the first 5

5

In [ ]:
ranArr.argmin()

7

In [ ]:
ranArr.shape  # returns shape of the array

(10,)

In [ ]:
arrx=arr.reshape(4,4)

In [ ]:
arrx.shape

(4, 4)

In [ ]:
arrx.dtype

dtype('int64')

#Numpy Indexing and Selection

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

#Broadcasting
Update multiple items in an array

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr  #It will change the original array as well #So taking a copy is important and work on the copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[0:3]=23
arr_copy

array([23, 23, 23, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr #original is not afffected, only the copy is changed

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#Indexing on 2D array

In [ ]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

#Fancy Indexing

First create matrix with different numbers in each row for a sample


In [ ]:
arr2dSample=np.zeros((10,10))
arr2dSample

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
len=arr2dSample.shape[1]
len

10

In [ ]:
for i in range(len):
  arr2dSample[[i]]=i
arr2dSample

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Now try fancy indexing on the above array:

In [ ]:
arr2dSample[[1]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr2dSample[[2,5,4,1,0,8]]  #Fancy Indexing

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

#Selection

In [ ]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
check=arr>4
check

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
#or it can be written this way
check=arr[arr>4]
check

array([ 5,  6,  7,  8,  9, 10])

#Numpy Operations

In [ ]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

<ipython-input-20-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

<ipython-input-21-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
5+arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#University of array functions

In [ ]:
arr=np.arange(0,10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr)

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-29-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])